#!/usr/bin/env python

import os
import sys
import argparse
import minuteToPdf

argParser = argparse.ArgumentParser(
    description="Pandoc wrapper for quick markdown transformation")

argParser.add_argument(
    "-i",
    "--in",
    type=str,
    help="Path to markdown file to be converted to a PDF"
)

argParser.add_argument(
    "-o",
    "--out",
    type=str,
    help="Output file path"
)

argParser.add_argument(
    "-u",
    "--url",
    type=str,
    help="Download URI to the markdown source"
)

if __name__ == "__main__":
    args = vars(argParser.parse_args())
    if args["url"] is None and args["in"] is None:
        print("There is no source, using stdout")

    if args["url"] is not None:
        markdownSource = minuteToPdf.getSourceFromURL(args["url"])
        if args["out"] is None:
            print("Please specify an output file name when using the download feature")
            sys.exit(-1)
    elif args["in"] is not None:
        markdownSource = minuteToPdf.getSourceFromFile(args["in"])
        if args["out"] is None:
            args["out"] = os.path.splitext(args["in"])[0]+'.pdf' 
    else:
        markdownSource = minuteToPdf.getSourceFromStdin()
        if args["out"] is None:
            print("Please specify an output file name when pulling from stdin")
            sys.exit(-1)

    parsedSource = minuteToPdf.parseMarkdown(markdownSource)
    minuteToPdf.convertToPdf(parsedSource, args["out"])
