#!/usr/bin/env python

import argparse
import minuteToPdf

argParser = argparse.ArgumentParser(
    description="Pandoc wrapper for quick markdown transformation")

argParser.add_argument(
    "-i",
    "--in",
    type=str,
    help="Path to markdown file to be converted to a PDF"
)

argParser.add_argument(
    "-o",
    "--out",
    type=str,
    help="Output file path"
)

argParser.add_argument(
    "-u",
    "--url",
    type=str,
    help="Download URI to the markdown source"
)

if __name__ == "__main__":
    args = vars(argParser.parse_args())
    if args["url"] is None and args["in"] is None:
        print("There is no source, using stdout")

    if args["url"] is not None:
        markdownSource = minuteToPdf.getSourceFromURL(args["url"])
    elif args["in"] is not None:
        markdownSource = minuteToPdf.getSourceFromFile(args["in"])
    else:
        markdownSource = minuteToPdf.getSourceFromStdin()

    parsedSource = minuteToPdf.parseMarkdown(markdownSource)
    minuteToPdf.convertToPdf(parsedSource, args["out"])
    print(parsedSource)
